apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-1125
  labels:
    app: backend-1125
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-1125
  template:
    metadata:
      labels:
        app: backend-1125
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/backend:latest
        ports:
        - containerPort: 3125
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-1125
spec:
  selector:
    app: backend-1125
  ports:
  - protocol: TCP
    port: 3125
    targetPort: 3125
  type: LoadBalancer
