version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "1125:1125"
    working_dir: /usr/src/1125_frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3125:3125"
    working_dir: /usr/src/1125_backend
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
