apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-1125
  labels:
    app: frontend-1125
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-1125
  template:
    metadata:
      labels:
        app: frontend-1125
    spec:
      containers:
      - name: frontend
        image: your-dockerhub-username/frontend:latest
        ports:
        - containerPort: 1125
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-1125
spec:
  selector:
    app: frontend-1125
  ports:
  - protocol: TCP
    port: 1125
    targetPort: 1125
  type: LoadBalancer
