apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-1125
  labels:
    app: frontend-1125
  annotations:
    description: "Frontend deployment for application"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-1125
  template:
    metadata:
      labels:
        app: frontend-1125
      annotations:
        description: "Pod template for frontend deployment"
    spec:
      containers:
      - name: frontend
        image: your-dockerhub-username/frontend:latest
        ports:
        - containerPort: 1125
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 1125
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 1125
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-1125
  labels:
    app: frontend-1125
  annotations:
    description: "Service for frontend deployment"
spec:
  selector:
    app: frontend-1125
  ports:
  - protocol: TCP
    port: 1125
    targetPort: 1125
  type: LoadBalancer
