apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment-1125
  labels:
    app: mongodb-1125
  annotations:
    description: "MongoDB deployment for application"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-1125
  template:
    metadata:
      labels:
        app: mongodb-1125
      annotations:
        description: "Pod template for MongoDB deployment"
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          exec:
            command:
            - "mongo"
            - "--eval"
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - "mongo"
            - "--eval"
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc-1125
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-1125
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: new-mongo-pv-1125
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-mongo-pv-1125
  labels:
    app: mongodb-1125
  annotations:
    description: "Persistent volume for MongoDB"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/your/new_mongo_data"
