apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment-1125
  labels:
    app: mongodb-1125
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-1125
  template:
    metadata:
      labels:
        app: mongodb-1125
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data2
          mountPath: /data/db
      volumes:
      - name: mongo-data2
        persistentVolumeClaim:
          claimName: mongo-pvc-1125
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-1125
spec:
  selector:
    app: mongodb-1125
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-1125
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
